/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Enums.TipoCliente;
import accesoDatos.ClienteData;
import entidades.Cliente;
import entidades.Conyugue;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

public class AltaClientes extends javax.swing.JInternalFrame {

    Cliente cli = new Cliente();
    ClienteData cData = new ClienteData();
// Declarar una variable de instancia para el JInternalFrame
    private Conyugues conyuguesFrame;

    public AltaClientes() {

        jConyugue = new JComboBox<>();
        initComponents();
        jLabel2.setToolTipText("Dato obligatorio");
        cargarCombo();
        jReingresar.setVisible(false);
        llenarEstado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon(getClass().getResource("/Iconos/61911070.jpg"));
            Image image = icon.getImage();
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLDNI = new javax.swing.JLabel();
        jDni = new javax.swing.JTextField();
        jCuil = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTrabajo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jDomi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jCiuda = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jcp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jMail = new javax.swing.JTextField();
        jGuardar = new javax.swing.JButton();
        jEstado = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jConyugue = new javax.swing.JComboBox<>();
        jSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jReingresar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameDeiconified(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNombreActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre: ");

        jLDNI.setBackground(new java.awt.Color(255, 255, 255));
        jLDNI.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLDNI.setForeground(new java.awt.Color(255, 255, 255));
        jLDNI.setText("DNI:");
        jLDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLDNIMouseEntered(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CUIL/CUIT:");

        jTipo.setToolTipText("");
        jTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTipoActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Conyugue:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Trabajo:");

        jTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTrabajoActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Domicilio:");

        jDomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDomiActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ciudad:");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Telefono:");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("C.P:");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("E-Mail:");

        jGuardar.setText("Guardar");
        jGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGuardarActionPerformed(evt);
            }
        });

        jEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jEstadoItemStateChanged(evt);
            }
        });
        jEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEstadoActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Estado Civil");

        jSalir.setText("Salir");
        jSalir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("(*)");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(204, 0, 0));
        jLabel13.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("(*)");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tipo Cliente:");

        jLabel15.setBackground(new java.awt.Color(204, 0, 0));
        jLabel15.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("(*)");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(204, 0, 0));
        jLabel16.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("(*)");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Alta Cliente.");

        jReingresar.setText("Reingresar");
        jReingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReingresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jConyugue, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCuil, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDni, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDomi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCiuda, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jcp, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jMail)
                                            .addComponent(jTel)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jReingresar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(jLabel14))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(jDomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(5, 5, 5)
                                                        .addComponent(jLabel16))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(jLabel6)))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(jCiuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabel11)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jcp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel13)
                                            .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1)))
                                    .addComponent(jLabel5))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel3)
                                    .addComponent(jCuil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLDNI)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jConyugue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGuardar)
                    .addComponent(jSalir)
                    .addComponent(jReingresar))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTrabajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTrabajoActionPerformed

    private void jDomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDomiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDomiActionPerformed

    private void jGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuardarActionPerformed
        // TODO add your handling code here:
        TipoCliente tipo;

        if (jTipo.getSelectedItem() == TipoCliente.PERSONA_FISICA) {
            if (jNombre.getText().equals("") && jCuil.getText().equals("") && jDni.getText().equals("") && jDomi.getText().equals("")
                    && jCiuda.getText().equals("") && jcp.getText().equals("") && jTrabajo.getText().equals("") && jTel.getText().equals("")
                    && jMail.getText().equals("")) {
                JOptionPane.showMessageDialog(
                        null,
                        "Por favor, complete todos los campos obligatorios:\n- Nombre\n- Cuil/Cuit\n- DNI\n- Domicilio\n- Ciudad\n"
                        + "- Codigo Postal\n- Trabajo\n- Telefono\n- Mail",
                        "Campos Incompletos",
                        JOptionPane.ERROR_MESSAGE
                );

                return;
            } else if (jCuil.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "El campo CUIL/CUIT se encuentra vacio!!.", "Error!", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (jDni.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "El campo DNI se encuentra vacio!!.", "Error!", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (jNombre.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "El campo Nombre se encuentra vacio!!.", "Error!", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (jDomi.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "El campo Domicilio se encuentra vacio!!.", "Error!", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (jCiuda.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "El campo Ciudad se encuentra vacio!!.", "Error!", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (jcp.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "El campo C.P. se encuentra vacio!!.", "Error!", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (jTrabajo.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "El campo Trabajo se encuentra vacio!!.", "Error!", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (jTel.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "El campo Telefono se encuentra vacio!!.", "Error!", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (jMail.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "El campo E-Mail se encuentra vacio!!.", "Error!", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (jEstado.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog(null, "Debe ingresar el estado civil!!.", "Error!", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!jNombre.getText().matches("^[\\p{L} ]+$")) {
                JOptionPane.showMessageDialog(null, "Ingrese un Nombre válido! (solo letras y espacios).",
                        "Error en el Nombre", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!jDomi.getText().matches("^[\\p{L} \\p{N}]+$")) {
                JOptionPane.showMessageDialog(null, "Ingrese un Domicilio válido! (solo letras, numeros y espacios).",
                        "Error en el Domicilio", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!jDni.getText().matches("[0-9]+")) {
                JOptionPane.showMessageDialog(null, "Ingrese un DNI válido! (solo números).",
                        "Error en el DNI", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!jCuil.getText().matches("[0-9]+")) {
                JOptionPane.showMessageDialog(null, "Ingrese un Cuil/Cuit válido! (solo números).",
                        "Error en el Cuil/Cuit", JOptionPane.ERROR_MESSAGE);

                return;
            }
            if (!jCiuda.getText().matches("^[\\p{L} ]+$")) {
                JOptionPane.showMessageDialog(null, "Ingrese una Ciudad válida! (solo letras y espacios).",
                        "Error en Ciudad", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!jcp.getText().matches("[0-9]+")) {
                JOptionPane.showMessageDialog(null, "Ingrese un Codigo Postal válido! (solo numeros).",
                        "Error en el Código Postal", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!jTrabajo.getText().matches("^[\\p{L} ]+$")) {
                JOptionPane.showMessageDialog(null, "Ingrese una Trabajo válido! (solo letras y espacios).",
                        "Error en Trabajo", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!jTel.getText().matches("[0-9]+")) {
                JOptionPane.showMessageDialog(null, "Ingrese un Teléfono válido! (solo numeros).",
                        "Error en el Telefono", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (jEstado.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog(null, "Seleccione el estado civil.");
                return;
            }
            if (jDni.getText().length() > 8) {
                JOptionPane.showMessageDialog(null, "La cantidad de digitos ingresados en DNI exede el limite permitido(8).");
                return;
            }

            long cuilExistente;
            for (Cliente c : cData.listarTodosClientes()) {
                cuilExistente = c.getCuilCuit();
                if (cuilExistente == Long.parseLong(jCuil.getText()) && c.isEstado() == true) {
                    JOptionPane.showMessageDialog(null, "El cliente ya se encuentra activo en la base de datos");
                    return;
                } else if (cuilExistente == Long.parseLong(jCuil.getText()) && c.isEstado() == false) {
                    int resp4 = JOptionPane.showConfirmDialog(null, "El cliente se encuentra inactivo en la base de datos.\n"
                            + "¿Desea dar de alta nuevamente al cliente?", "Atención!",
                            JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                    if (resp4 == 0) {
                        jReingresar.setVisible(true);
                        jEstado.setSelectedItem("");
                        jDni.setText("");
                        jDomi.setText("");
                        jConyugue.setSelectedItem("");
                        jCiuda.setText("");
                        jcp.setText("");
                        jNombre.setText("");
                        jTrabajo.setText("");
                        jTel.setText("");
                        jMail.setText("");
                        return;
                    } else {
                        return;
                    }
                }
            }

            int resp = JOptionPane.showConfirmDialog(null, "¿Desea guardar los datos ingresados?", "Atención!",
                    JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if (resp == 0) {
                tipo = (TipoCliente) jTipo.getSelectedItem();

                Conyugue con;
                if (jConyugue == null) {

                    con = null;
                } else {
                    con = (Conyugue) jConyugue.getSelectedItem();
                    String nom = jNombre.getText();
                    int dni = Integer.parseInt(jDni.getText());
                    long cuil = Long.parseLong(jCuil.getText());
                    String dom = jDomi.getText();
                    String ciu = jCiuda.getText();
                    String cp = jcp.getText();
                    String trabajo = jTrabajo.getText();
                    String tel = jTel.getText();
                    String mail = jMail.getText();
                    boolean est = true;

                    cli = new Cliente(con, tipo, nom, dni, cuil, trabajo, dom, ciu, cp, tel, mail, est);

                    cData.agregarClienteFisico(cli);

                }
            }
            borrar();
        }
        if (jTipo.getSelectedItem() == TipoCliente.PERSONA_JURIDICA) {
            if (jNombre.getText().equals("") && jCuil.getText().equals("") && jDomi.getText().equals("")
                    && jCiuda.getText().equals("") && jcp.getText().equals("") && jTrabajo.getText().equals("") && jTel.getText().equals("")
                    && jMail.getText().equals("")) {
                JOptionPane.showMessageDialog(
                        null,
                        "Por favor, complete todos los campos obligatorios:\n- Nombre\n- Cuil/Cuit\n- Domicilio\n- Ciudad\n"
                        + "- Codigo Postal\n- Trabajo\n- Telefono\n- Mail",
                        "Campos Incompletos",
                        JOptionPane.ERROR_MESSAGE
                );

                return;
            } else if (jCuil.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "El campo Cuil/Cuit se encuentra vacio!!.", "Error!", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (jNombre.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "El campo Nombre se encuentra vacio!!.", "Error!", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (jDomi.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "El campo Domicilio se encuentra vacio!!.", "Error!", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (jCiuda.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "El campo Ciudad se encuentra vacio!!.", "Error!", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (jcp.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "El campo C.P. se encuentra vacio!!.", "Error!", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (jTrabajo.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "El campo Trabajo se encuentra vacio!!.", "Error!", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (jTel.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "El campo Telefono se encuentra vacio!!.", "Error!", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (jMail.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "El campo E-Mail se encuentra vacio!!.", "Error!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!jNombre.getText().matches("^[\\p{L} ]+$")) {
                JOptionPane.showMessageDialog(null, "Ingrese un Nombre válido! (solo letras y espacios).",
                        "Error en el Nombre", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!jDomi.getText().matches("^[\\p{L} \\p{N}]+$")) {
                JOptionPane.showMessageDialog(null, "Ingrese un Domicilio válido! (solo letras, numeros y espacios).",
                        "Error en Domicilio", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!jCuil.getText().matches("[0-9]+")) {
                JOptionPane.showMessageDialog(null, "Ingrese un DNI válido! (solo números).",
                        "Error en el DNI", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!jCiuda.getText().matches("^[\\p{L} ]+$")) {
                JOptionPane.showMessageDialog(null, "Ingrese una Ciudad válido! (solo letras y espacios).",
                        "Error en Ciudad", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!jcp.getText().matches("[0-9]+")) {
                JOptionPane.showMessageDialog(null, "Ingrese un Codigo Postal válido! (solo numeros).",
                        "Error en el Código Postal", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!jTrabajo.getText().matches("^[\\p{L} ]+$")) {
                JOptionPane.showMessageDialog(null, "Ingrese una Trabajo válido! (solo letras y espacios).",
                        "Error en Trabajo", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!jTel.getText().matches("[0-9]+")) {
                JOptionPane.showMessageDialog(null, "Ingrese un Teléfono válido! (solo numeros).",
                        "Error en el Telefono", JOptionPane.ERROR_MESSAGE);
                return;
            }

            long cuilExistente;
            for (Cliente c : cData.listarTodosClientes()) {
                cuilExistente = c.getCuilCuit();
                if (cuilExistente == Long.parseLong(jCuil.getText()) && c.isEstado() == true) {
                    JOptionPane.showMessageDialog(null, "El cliente ya se encuentra activo en la base de datos");
                    return;
                } else if (cuilExistente == Long.parseLong(jCuil.getText()) && c.isEstado() == false) {
                    int resp3 = JOptionPane.showConfirmDialog(null, "El cliente se encuentra inactivo en la base de datos.\n"
                            + "¿Desea dar de alta nuevamente al cliente?", "Atención!",
                            JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                    if (resp3 == 0) {
                        jReingresar.setVisible(true);
                        jEstado.setSelectedItem("");
                        jDni.setText("");
                        jDomi.setText("");
                        jConyugue.setSelectedItem("");
                        jCiuda.setText("");
                        jcp.setText("");
                        jNombre.setText("");
                        jTrabajo.setText("");
                        jTel.setText("");
                        jMail.setText("");
                        return;
                    } else {
                        return;
                    }
                }
            }

            int resp2 = JOptionPane.showConfirmDialog(null, "¿Desea guardar los datos ingresados?", "Atención!",
                    JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if (resp2 == 0) {
                tipo = (TipoCliente) jTipo.getSelectedItem();
                String nom = jNombre.getText();
                long cuil = Long.parseLong(jCuil.getText());
                String dom = jDomi.getText();
                String ciu = jCiuda.getText();
                String cp = jcp.getText();
                String trabajo = jTrabajo.getText();
                String tel = jTel.getText();
                String mail = jMail.getText();
                boolean est = true;

                cli = new Cliente(tipo, nom, cuil, trabajo, dom, ciu, cp, tel, mail, est);

                cData.agregarClienteJuridico(cli);
                borrar();
            }

        }
    }//GEN-LAST:event_jGuardarActionPerformed

    private void jEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEstadoActionPerformed
        // TODO add your handling code here:
        if (jEstado != null) { // Verifica si jEstado no es null
            if (jEstado.getSelectedItem().equals("Soltero/a")) {
                if (jConyugue != null) { // Verifica si jConyugue no es null
                    jConyugue.setEnabled(false);
                }
                if (conyuguesFrame != null && conyuguesFrame.isVisible()) {
                    conyuguesFrame.dispose();
                }
            } else if (jEstado.getSelectedItem().equals("Casado/a") || jEstado.getSelectedItem().equals("Concubinato")) {
                if (conyuguesFrame != null && conyuguesFrame.isVisible()) {
                    conyuguesFrame.dispose();
                }

                conyuguesFrame = new Conyugues();
                Menu.Escritorio.add(conyuguesFrame);
                conyuguesFrame.toFront();
                conyuguesFrame.setVisible(true);
            }
        }
    }//GEN-LAST:event_jEstadoActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jSalirActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_formMouseDragged

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_formMouseMoved

    private void formInternalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameDeiconified
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameDeiconified

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTipoActionPerformed
        // TODO add your handling code here:
        if (jTipo.getSelectedItem() == TipoCliente.PERSONA_JURIDICA) {
            jEstado.setEnabled(false);
            jDni.setEnabled(false);
            jConyugue.setEnabled(false);

        } else if (jTipo.getSelectedItem() == TipoCliente.PERSONA_FISICA) {
            jEstado.setEnabled(true);
            jDni.setEnabled(true);
            jConyugue.setEnabled(true);
        }

    }//GEN-LAST:event_jTipoActionPerformed

    private void jLDNIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLDNIMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jLDNIMouseEntered

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setText("(*)");
        jLabel2.setToolTipText("Dato obligatorio");
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // TODO add your handling code here:
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setText("(*)");
        jLabel2.setToolTipText("Dato obligatorio");
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        // TODO add your handling code here:
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setText("(*)");
        jLabel2.setToolTipText("Dato obligatorio");
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        // TODO add your handling code here:
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setText("(*)");
        jLabel2.setToolTipText("Dato obligatorio");
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNombreActionPerformed

    private void jEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jEstadoItemStateChanged
        // TODO add your handling code here:
        if (jEstado.getSelectedItem().equals("Soltero/a")) {

            if (conyuguesFrame != null && conyuguesFrame.isVisible()) {
                conyuguesFrame.dispose(); // Cierra el JInternalFrame si ya está abierto
            }
        } else if (jEstado.getSelectedItem().equals("Casado/a") || jEstado.getSelectedItem().equals("Concubinato")) {
            if (conyuguesFrame != null && conyuguesFrame.isVisible()) {
                conyuguesFrame.dispose(); // Cierra el JInternalFrame si ya está abierto
            }

        }

    }//GEN-LAST:event_jEstadoItemStateChanged

    private void jReingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReingresarActionPerformed
        // TODO add your handling code here:

        long cuil = Long.parseLong(jCuil.getText());
        cli = cData.buscarClientePorCuilCuit(cuil);
        cData.reingresarCliente(cli.getIdCliente());
        borrar();
    }//GEN-LAST:event_jReingresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jCiuda;
    private javax.swing.JComboBox<Conyugue> jConyugue;
    private javax.swing.JTextField jCuil;
    private javax.swing.JTextField jDni;
    private javax.swing.JTextField jDomi;
    private javax.swing.JComboBox<String> jEstado;
    private javax.swing.JButton jGuardar;
    private javax.swing.JLabel jLDNI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jMail;
    private javax.swing.JTextField jNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jReingresar;
    private javax.swing.JButton jSalir;
    private javax.swing.JTextField jTel;
    private javax.swing.JComboBox<TipoCliente> jTipo;
    private javax.swing.JTextField jTrabajo;
    private javax.swing.JTextField jcp;
    // End of variables declaration//GEN-END:variables

    public void cargarCombo() {
        jTipo.addItem(null);
        jTipo.addItem(TipoCliente.PERSONA_FISICA);
        jTipo.addItem(TipoCliente.PERSONA_JURIDICA);
    }

    public void agregarElementoAComboBox(Conyugue elemento) {
//         System.out.println("Agregando elemento: " + elemento);
        jConyugue.addItem(elemento);
    }

    public void llenarEstado() {
        jEstado.addItem("");
        jEstado.addItem("Soltero/a");
        jEstado.addItem("Casado/a");
        jEstado.addItem("Concubinato");
    }

    public void borrar() {
        jTipo.removeAll();
        jEstado.setSelectedItem("");
        jDni.setText("");
        jDomi.setText("");
        jConyugue.setSelectedItem("");
        jCiuda.setText("");
        jcp.setText("");
        jNombre.setText("");
        jTrabajo.setText("");
        jTel.setText("");
        jCuil.setText("");
        jMail.setText("");

    }
}
