/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Enums.Accesibilidad;
import Enums.TipoInmueble;
import Enums.Zona;
import accesoDatos.InmuebleData;
import accesoDatos.PropietarioData;
import entidades.Inmueble;
import entidades.Propietario;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Usuario
 */
public class ManejoInmuebles extends javax.swing.JInternalFrame {

    InmuebleData iDa = new InmuebleData(); 
    Inmueble inm = new Inmueble();
    PropietarioData pDa = new PropietarioData();
    Propietario prop = new Propietario();
    
    public final DefaultTableModel modelo = new DefaultTableModel() {

        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };
    private final TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo);
    
    public ManejoInmuebles() {
        initComponents();
        cargarComboTipoInmueble();
        cargarComboZona();
        cargarComboAccesibilidad();
        seteoInicial();
        jrbAlquiler.setSelected(true);
        inm.setAlquilerVenta("Alquiler");
        jrbDisponible.setSelected(true);
        inm.setDisponible(true);
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbTipoInmueble = new javax.swing.JComboBox<>();
        jrbAlquiler = new javax.swing.JRadioButton();
        jrbVenta = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jcbZona = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jtfSuperficieI = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfAmbientes = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfDormitorios = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfBaños = new javax.swing.JTextField();
        jrbPatio = new javax.swing.JRadioButton();
        jrbCochera = new javax.swing.JRadioButton();
        jrbQuincho = new javax.swing.JRadioButton();
        jrbPileta = new javax.swing.JRadioButton();
        jrbMascotas = new javax.swing.JRadioButton();
        jrbNiños = new javax.swing.JRadioButton();
        jrbDisponible = new javax.swing.JRadioButton();
        jbSalir = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jcbAccesibilidad = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jtfPrecioI = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtfPrecioF = new javax.swing.JTextField();
        jtfSuperficieF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jbBuscarTodos = new javax.swing.JButton();

        setAutoscrolls(true);
        setFrameIcon(null);
        setPreferredSize(new java.awt.Dimension(1050, 850));

        jLabel1.setFont(new java.awt.Font("Ebrima", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Busqueda Inmuebles");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Tipo de Propiedad");

        jcbTipoInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoInmuebleActionPerformed(evt);
            }
        });

        jrbAlquiler.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrbAlquiler.setForeground(new java.awt.Color(102, 102, 102));
        jrbAlquiler.setText("Alquiler");
        jrbAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAlquilerActionPerformed(evt);
            }
        });

        jrbVenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrbVenta.setForeground(new java.awt.Color(102, 102, 102));
        jrbVenta.setText("Venta");
        jrbVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbVentaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Zona");

        jcbZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbZonaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Superficie");

        jtfSuperficieI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSuperficieIActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Accesibilidad");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Ambientes");

        jtfAmbientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAmbientesActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Dormitorios");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Baños");

        jtfBaños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBañosActionPerformed(evt);
            }
        });

        jrbPatio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrbPatio.setForeground(new java.awt.Color(102, 102, 102));
        jrbPatio.setText("Patio");

        jrbCochera.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrbCochera.setForeground(new java.awt.Color(102, 102, 102));
        jrbCochera.setText("Cochera");

        jrbQuincho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrbQuincho.setForeground(new java.awt.Color(102, 102, 102));
        jrbQuincho.setText("Quincho");

        jrbPileta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrbPileta.setForeground(new java.awt.Color(102, 102, 102));
        jrbPileta.setText("Pileta");

        jrbMascotas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrbMascotas.setForeground(new java.awt.Color(102, 102, 102));
        jrbMascotas.setText("Mascotas");

        jrbNiños.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrbNiños.setForeground(new java.awt.Color(102, 102, 102));
        jrbNiños.setText("Niños");
        jrbNiños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNiñosActionPerformed(evt);
            }
        });

        jrbDisponible.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrbDisponible.setForeground(new java.awt.Color(102, 102, 102));
        jrbDisponible.setText("Disponible");
        jrbDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDisponibleActionPerformed(evt);
            }
        });

        jbSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbSalir.setForeground(new java.awt.Color(102, 102, 102));
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbBuscar.setForeground(new java.awt.Color(102, 102, 102));
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jcbAccesibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAccesibilidadActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Precio");

        jtfPrecioI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPrecioIActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Hasta");

        jtfSuperficieF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSuperficieFActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Hasta");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Inmuebles");

        jbBuscarTodos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbBuscarTodos.setForeground(new java.awt.Color(102, 102, 102));
        jbBuscarTodos.setText("Buscar Todos");
        jbBuscarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(413, Short.MAX_VALUE)
                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(346, 346, 346))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(237, 237, 237))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(91, 91, 91)
                                    .addComponent(jcbAccesibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jcbTipoInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jcbZona, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jtfPrecioI, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel14)
                                            .addGap(18, 18, 18)
                                            .addComponent(jtfPrecioF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtfAmbientes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtfDormitorios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtfBaños, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel13)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jrbAlquiler)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jrbVenta)))
                                            .addGap(18, 18, 18)
                                            .addComponent(jbBuscarTodos)))
                                    .addGap(6, 6, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jtfSuperficieI, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel15)
                                                .addGap(18, 18, 18)
                                                .addComponent(jtfSuperficieF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jrbMascotas)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jrbNiños)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jrbDisponible))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jrbPatio)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jrbCochera)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jrbQuincho)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jrbPileta)))
                                            .addGap(1, 1, 1)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbTipoInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbAlquiler)
                    .addComponent(jrbVenta)
                    .addComponent(jbBuscarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel6))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfSuperficieI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfSuperficieF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtfPrecioI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfPrecioF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbAccesibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbPatio)
                    .addComponent(jrbCochera)
                    .addComponent(jrbQuincho)
                    .addComponent(jrbPileta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfAmbientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDormitorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfBaños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbMascotas)
                    .addComponent(jrbNiños)
                    .addComponent(jrbDisponible))
                .addGap(36, 36, 36)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbTipoInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoInmuebleActionPerformed
    }//GEN-LAST:event_jcbTipoInmuebleActionPerformed

    private void jrbVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbVentaActionPerformed
     if(jrbVenta.isSelected()){
         inm.setAlquilerVenta("Venta");
         jrbAlquiler.setSelected(false);
     }else{
         inm.setAlquilerVenta("Alquiler");
         jrbAlquiler.setSelected(true);
     }
        System.out.println(inm.getAlquilerVenta());
    }//GEN-LAST:event_jrbVentaActionPerformed

    private void jrbAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAlquilerActionPerformed
     if(jrbAlquiler.isSelected()){
         inm.setAlquilerVenta("Alquiler");
         jrbVenta.setSelected(false);
     
     }else{
         inm.setAlquilerVenta("Venta");
         jrbVenta.setSelected(true);
     
     }
     System.out.println(inm.getAlquilerVenta());
    }//GEN-LAST:event_jrbAlquilerActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed

        int superI, superF, ambientes, dormitorios, baños;
        Double precioI, precioF;
        
        
        modelo.setRowCount(0);
        inm.setTipo((TipoInmueble) jcbTipoInmueble.getSelectedItem());

        inm.setZona((Zona) jcbZona.getSelectedItem());

        if (jtfSuperficieI.getText().equals("")) {
            superI = 0;
        } else {
            try {
                superI = Integer.parseInt(jtfSuperficieI.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Debe Ingresar un Numero Valido");
                return;
            }
        }
        
        
        
        if (jtfSuperficieF.getText().equals("")) {
        superF = Integer.MAX_VALUE;
        }else{
        try {
           superF = Integer.parseInt(jtfSuperficieF.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Debe Ingresar un Numero Valido");
            return;
        }
        }

        inm.setAccesibilidad((Accesibilidad) jcbAccesibilidad.getSelectedItem());

        if(jtfAmbientes.getText().equals("")){
        ambientes = 0;
        }else{
        try {
           ambientes = Integer.parseInt(jtfAmbientes.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Debe Ingresar un Numero Valido");
            return;
        }
        }
        
        if(jtfDormitorios.getText().equals("")){
            dormitorios = 0;
        }else{
        try {
            dormitorios = Integer.parseInt(jtfDormitorios.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Debe Ingresar un Numero Valido");
            return;
        }
        }
        
        if(jtfBaños.getText().equals("")){
            baños = 0;
        }else{
        try {
            baños = Integer.parseInt(jtfBaños.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Debe Ingresar un Numero Valido");
            return;
        }
        }
        
        
        if(jtfPrecioI.getText().equals("")){
        precioI = 0.0;
        }else{
        try {
          precioI = Double.parseDouble(jtfPrecioI.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Debe Ingresar un Numero Valido");
            return;
        }
        }
        
        if(jtfPrecioF.getText().equals("")){
            precioF = 99999999999.00;
        }else{
        try {
            precioF = Double.parseDouble(jtfPrecioF.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Debe Ingresar un Numero Valido");
            return;
        }
        }

        //inm.setSuperficie(Integer.parseInt(jtfSuperficieI.getText()));
        //inm.setPrecioTasado(Double.parseDouble(jtfPrecioI.getText()));
        inm.setAmbientes(ambientes);
        inm.setDormitorios(dormitorios);
        inm.setBaños(baños);
        inm.setPatio(jrbPatio.isSelected());
        inm.setCochera(jrbCochera.isSelected());
        inm.setQuincho(jrbQuincho.isSelected());
        inm.setPileta(jrbPileta.isSelected());
        inm.setMascotas(jrbMascotas.isSelected());
        inm.setNiños(jrbNiños.isSelected());
        inm.setDisponible(jrbDisponible.isSelected());
       // try {
            for (Inmueble in : iDa.buscarPropiedades(inm, superI, superF, precioI, precioF)) {
                modelo.addRow(new Object[]{
                    in.getIdInmueble(), in.getProp().getNombre(), in.getDireccion(), in.getZona(), in.getTipo(), in.getSuperficie(), in.getPrecioTasado(), in.getAmbientes(), in.getDormitorios(), in.getAccesibilidad()
                });
                System.out.println(in.getDescripcion());
            }

        //} catch (Exception e) {
          //  JOptionPane.showMessageDialog(null, "No se Pudo Cargar la Propiedad");
        //}

        seteoInicial();
        
        

    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jcbZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbZonaActionPerformed
    }//GEN-LAST:event_jcbZonaActionPerformed

    private void jtfSuperficieIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSuperficieIActionPerformed

    }//GEN-LAST:event_jtfSuperficieIActionPerformed

    private void jcbAccesibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAccesibilidadActionPerformed
    }//GEN-LAST:event_jcbAccesibilidadActionPerformed

    private void jrbDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDisponibleActionPerformed
       if(jrbDisponible.isSelected() == false){
           inm.setDisponible(false);
       }else{
           inm.setDisponible(true);
       }
        System.out.println(inm.isDisponible());
    }//GEN-LAST:event_jrbDisponibleActionPerformed

    private void jtfPrecioIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPrecioIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPrecioIActionPerformed

    private void jtfSuperficieFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSuperficieFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSuperficieFActionPerformed

    private void jtfBañosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBañosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfBañosActionPerformed

    private void jtfAmbientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAmbientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAmbientesActionPerformed

    private void jrbNiñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNiñosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbNiñosActionPerformed

    private void jbBuscarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarTodosActionPerformed
    modelo.setRowCount(0);
    if(jrbAlquiler.isSelected()){
     for (Inmueble in : iDa.buscarPropiedadesAlqVta("Alquiler", jrbDisponible.isSelected())) {
                modelo.addRow(new Object[]{
                    in.getIdInmueble(), in.getProp().getNombre(), in.getDireccion(), in.getZona(), in.getTipo(), in.getSuperficie(), in.getPrecioTasado(), in.getAmbientes(), in.getDormitorios(), in.getAccesibilidad()
                });
                System.out.println(in.getDescripcion());
            }
    }else{
    for (Inmueble in : iDa.buscarPropiedadesAlqVta("Venta", jrbDisponible.isSelected())) {
                modelo.addRow(new Object[]{
                    in.getIdInmueble(), in.getProp().getNombre(), in.getDireccion(), in.getZona(), in.getTipo(), in.getSuperficie(), in.getPrecioTasado(), in.getAmbientes(), in.getDormitorios(), in.getAccesibilidad()
                });
                System.out.println(in.getDescripcion());
            }
    }
        //} catch (Exception e) {
          //  JOptionPane.showMessageDialog(null, "No se Pudo Cargar la Propiedad");
        //}

        seteoInicial();
    }//GEN-LAST:event_jbBuscarTodosActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    Inmueble in = new Inmueble();
    InmuebleData inD = new InmuebleData();
        if (evt.getClickCount() == 2) {
            int fila = jTable1.getSelectedRow(); // Obtiene la fila seleccionada al hacer doble clic
            if (fila >= 0) {
                ModificacionBajaInmueble mbi= new ModificacionBajaInmueble(); //Creo un objeto del internalFrame
                Menu.Escritorio.add(mbi);//llamo al escritorio del menu y agrego el internal
                mbi.toFront();//con este metodo hago que el internal se muestre delante del internal que lo llama
                mbi.setVisible(true);//metodo para mostrar el internal 
                this.setVisible(false);
            }
            if (fila != -1) {
                int idInmueble = (int) jTable1.getValueAt(fila, 0); // creo una variable y e asigno el valor a transferir
                in = inD.buscarPropiedadId(idInmueble);
                }
                

                // Accede al JInternalFrame " ModificarCliente" y llama al método para establecer el valor en el JTextField
                ModificacionBajaInmueble clienteF = obtenerModificarFrame();//metodo que hace referncia a  ModificarCliente
                 
                if (clienteF != null) {
                    clienteF.setTextFieldValue(in);//Paso por parametros los datos que va a recibir  ModificarCliente
                }
            }
        
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbBuscarTodos;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Accesibilidad> jcbAccesibilidad;
    private javax.swing.JComboBox<TipoInmueble> jcbTipoInmueble;
    private javax.swing.JComboBox<Zona> jcbZona;
    private javax.swing.JRadioButton jrbAlquiler;
    private javax.swing.JRadioButton jrbCochera;
    private javax.swing.JRadioButton jrbDisponible;
    private javax.swing.JRadioButton jrbMascotas;
    private javax.swing.JRadioButton jrbNiños;
    private javax.swing.JRadioButton jrbPatio;
    private javax.swing.JRadioButton jrbPileta;
    private javax.swing.JRadioButton jrbQuincho;
    private javax.swing.JRadioButton jrbVenta;
    private javax.swing.JTextField jtfAmbientes;
    private javax.swing.JTextField jtfBaños;
    private javax.swing.JTextField jtfDormitorios;
    private javax.swing.JTextField jtfPrecioF;
    private javax.swing.JTextField jtfPrecioI;
    private javax.swing.JTextField jtfSuperficieF;
    private javax.swing.JTextField jtfSuperficieI;
    // End of variables declaration//GEN-END:variables




private void cargarComboTipoInmueble() {

    jcbTipoInmueble.addItem(null);
    jcbTipoInmueble.addItem(TipoInmueble.CASA);
    jcbTipoInmueble.addItem(TipoInmueble.DEPARTAMENTO);
    jcbTipoInmueble.addItem(TipoInmueble.DUPLEX);
    jcbTipoInmueble.addItem(TipoInmueble.GALPON);
    jcbTipoInmueble.addItem(TipoInmueble.LOCAL);
    jcbTipoInmueble.addItem(TipoInmueble.LOTE);
    jcbTipoInmueble.addItem(TipoInmueble.MONOAMBIENTE);
    jcbTipoInmueble.addItem(TipoInmueble.OFICINA);
    jcbTipoInmueble.addItem(TipoInmueble.QUINTA);
    jcbTipoInmueble.addItem(TipoInmueble.TERRENO);

    }


private void cargarComboZona() {
jcbZona.addItem(null);
jcbZona.addItem(Zona.RESIDENCIAL);
jcbZona.addItem(Zona.COMERCIAL);
jcbZona.addItem(Zona.INDUSTRIAL);
jcbZona.addItem(Zona.TURISTICA);
jcbZona.addItem(Zona.DE_RECREACION);
jcbZona.addItem(Zona.EDUCATIVA);
jcbZona.addItem(Zona.HISTÓRICA);
jcbZona.addItem(Zona.RURAL);


}

private void cargarComboAccesibilidad(){
jcbAccesibilidad.addItem(null);
jcbAccesibilidad.addItem(Accesibilidad.ESTANDAR);
jcbAccesibilidad.addItem(Accesibilidad.ESCALERAS);
jcbAccesibilidad.addItem(Accesibilidad.RAMPA_ACCESO);
jcbAccesibilidad.addItem(Accesibilidad.ASENSOR);

}

private void seteoInicial(){
    
    jcbAccesibilidad.setSelectedIndex(-1);
    jcbTipoInmueble.setSelectedIndex(-1);
    jcbZona.setSelectedIndex(-1);
    jrbAlquiler.setSelected(true);
    jrbVenta.setSelected(false);
    jrbCochera.setSelected(false);
    jrbDisponible.setSelected(true);
    jrbMascotas.setSelected(false);
    jrbNiños.setSelected(false);
    jrbPatio.setSelected(false);
    jrbPileta.setSelected(false);
    jrbQuincho.setSelected(false);
    jtfAmbientes.setText("");
    jtfBaños.setText("");
    jtfDormitorios.setText("");
    jtfPrecioI.setText("");
    jtfPrecioF.setText("");
    jtfSuperficieI.setText("");
    jtfSuperficieF.setText("");

}


private void armarCabecera() {

        modelo.addColumn("ID");
        modelo.addColumn("Propietario");
        modelo.addColumn("Direccion");
        modelo.addColumn("Zona");
        modelo.addColumn("Tipo");
        modelo.addColumn("Superficie");
        modelo.addColumn("Precio");
        modelo.addColumn("Ambientes");
        modelo.addColumn("Dormitorios");
        modelo.addColumn("Accesibilidad");
       // modelo.addColumn("Baños");
      
        //modelo.addColumn("Patio");
        //modelo.addColumn("Cochera");
        //modelo.addColumn("Quincho");
        //modelo.addColumn("Pileta");
        //modelo.addColumn("Niños");
        //modelo.addColumn("Mascota");
        //modelo.addColumn("Estado");
        jTable1.setModel(modelo);
    }

private ModificacionBajaInmueble obtenerModificarFrame() {
        JInternalFrame[] frames = getDesktopPane().getAllFrames();
        for (JInternalFrame frame : frames) {
            if (frame instanceof ModificacionBajaInmueble) {
                return (ModificacionBajaInmueble) frame;
            }
        }
        return null; // Devuelve null si no se encuentra el frame "AltaClientes"
    }

    int getSelectedRow() {
        int fila = jTable1.getSelectedRow(); //To change body of generated methods, choose Tools | Templates.
        return fila;
    }

}
