/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Enums.TipoCliente;
import accesoDatos.PagoVentaData;
import entidades.Venta;
import java.awt.Graphics;
import java.awt.Image;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Compaq
 */
public class PagoVenta extends javax.swing.JInternalFrame {

    /**
     * Creates new form PagoVenta
     */
    private Ventas ventasFrame;

    public PagoVenta() {
        jVenta = new JComboBox<>();
        initComponents();
        jtHono.setEditable(false);
        jtComi.setEditable(false);
        llenarMoneda();
        jtInteres.setEditable(false);
        llenarTipoPago();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon(getClass().getResource("/Iconos/61911070.jpg"));
            Image image = icon.getImage();
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jVenta = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jForma = new javax.swing.JComboBox<>();
        jdPago = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLMonto = new javax.swing.JLabel();
        jtMonto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtCantCuotas = new javax.swing.JTextField();
        jdVto = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtValorCuota = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jcMoneda = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jtPorcInt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtPorcHon = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtHono = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtPorcCom = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtComi = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDesc = new javax.swing.JTextPane();
        jLabel18 = new javax.swing.JLabel();
        jGuardar = new javax.swing.JButton();
        jSalir = new javax.swing.JButton();
        jtInteres = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro Pago de Venta");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Venta: ");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Forma de Pago: ");

        jForma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormaActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha de Pago: ");

        jLMonto.setBackground(new java.awt.Color(255, 255, 255));
        jLMonto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLMonto.setForeground(new java.awt.Color(255, 255, 255));
        jLMonto.setText("Monto Pagado: ");

        jtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtMontoActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cantidad Cuotas: ");

        jtCantCuotas.setPreferredSize(new java.awt.Dimension(99, 24));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha 1er Vto.");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Valor de Cuota: ");

        jtValorCuota.setPreferredSize(new java.awt.Dimension(99, 24));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Moneda: ");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mora:");

        jtPorcInt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtPorcIntFocusLost(evt);
            }
        });
        jtPorcInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPorcIntActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("% diario.");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Honorarios: ");

        jtPorcHon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtPorcHonFocusLost(evt);
            }
        });
        jtPorcHon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPorcHonActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("%");

        jtHono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtHonoActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ARS");

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Comisión: ");

        jtPorcCom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtPorcComFocusLost(evt);
            }
        });
        jtPorcCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPorcComActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("%");

        jtComi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtComiActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("ARS");

        jScrollPane1.setViewportView(jtDesc);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Descripción del Pago");

        jGuardar.setText("Guardar");
        jGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGuardarActionPerformed(evt);
            }
        });

        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });

        jtInteres.setToolTipText("");
        jtInteres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtInteresActionPerformed(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("ARS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jForma, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtValorCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtCantCuotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtPorcInt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtPorcHon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtHono, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jtPorcCom, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtComi, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLMonto)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtMonto)
                                            .addComponent(jdPago, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                            .addComponent(jcMoneda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jdVto, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(85, 85, 85))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jGuardar)
                        .addGap(156, 156, 156)
                        .addComponent(jSalir)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(jdPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLMonto)
                    .addComponent(jtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jtCantCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jtValorCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7)
                        .addComponent(jdVto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jtPorcInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jtInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jtPorcHon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jtHono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtPorcCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jtComi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGuardar)
                    .addComponent(jSalir))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtMontoActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jSalirActionPerformed

    private void jGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuardarActionPerformed
        // TODO add your handling code here:

        controlDeEntrada();
        int resp = JOptionPane.showConfirmDialog(null, "¿Desea guardar los datos ingresados?", "Atención!",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (resp == 0) {
            if (jForma.getSelectedItem().equals("Efectivo") || jForma.getSelectedItem().equals("Transferencia Bancaria")
                    || jForma.getSelectedItem().equals("Cheque Bancario")) {

                pagoContado();
            } else {
                pagoCuotas();
            }
        }


    }//GEN-LAST:event_jGuardarActionPerformed

    private void jtComiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtComiActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtComiActionPerformed

    private void jFormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormaActionPerformed
        // TODO add your handling code here:
        if (jForma.getSelectedItem().equals("Efectivo") || jForma.getSelectedItem().equals("Transferencia Bancaria")
                || jForma.getSelectedItem().equals("Cheque Bancario")) {
            jtCantCuotas.setEnabled(false);
            jtValorCuota.setEnabled(false);
            jdVto.setEnabled(false);
            jtPorcInt.setEnabled(false);
            jLMonto.setText("Monto Pagado:");

        } else {
            jtCantCuotas.setEnabled(true);
            jtValorCuota.setEnabled(true);
            jdVto.setEnabled(true);
            jtPorcInt.setEnabled(true);
            jLMonto.setText("Pago Inicial:");
            
        }
    }//GEN-LAST:event_jFormaActionPerformed

    private void jtHonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtHonoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtHonoActionPerformed

    private void jtInteresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtInteresActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtInteresActionPerformed

    private void jtPorcIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPorcIntActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtPorcIntActionPerformed

    private void jtPorcHonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPorcHonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtPorcHonActionPerformed

    private void jtPorcComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPorcComActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtPorcComActionPerformed

    private void jtPorcIntFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPorcIntFocusLost
        // TODO add your handling code here:
          double vCuota = Double.parseDouble(jtValorCuota.getText());
        double cuentaInt = vCuota * (Double.parseDouble(jtPorcInt.getText())) / 100;
        jtInteres.setText(String.valueOf(cuentaInt));
    }//GEN-LAST:event_jtPorcIntFocusLost

    private void jtPorcHonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPorcHonFocusLost
        // TODO add your handling code here:
         double monto = Double.parseDouble(jtMonto.getText());
         System.out.println(monto);
         double cuentaHon = (monto * Double.parseDouble(jtPorcHon.getText())) / 100;//Calculo el porcentaje de honorarios
        jtHono.setText(String.valueOf(cuentaHon));//Paso el valor de la cuenta la jtextfield
    }//GEN-LAST:event_jtPorcHonFocusLost

    private void jtPorcComFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPorcComFocusLost
        // TODO add your handling code here:
         double monto = Double.parseDouble(jtMonto.getText());
        double cuentaComi = monto * (Double.parseDouble(jtPorcCom.getText())) / 100;
        jtComi.setText(String.valueOf(cuentaComi));
    }//GEN-LAST:event_jtPorcComFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jForma;
    private javax.swing.JButton jGuardar;
    private javax.swing.JLabel jLMonto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Venta> jVenta;
    private javax.swing.JComboBox<String> jcMoneda;
    private com.toedter.calendar.JDateChooser jdPago;
    private com.toedter.calendar.JDateChooser jdVto;
    private javax.swing.JTextField jtCantCuotas;
    private javax.swing.JTextField jtComi;
    private javax.swing.JTextPane jtDesc;
    private javax.swing.JTextField jtHono;
    private javax.swing.JTextField jtInteres;
    private javax.swing.JTextField jtMonto;
    private javax.swing.JTextField jtPorcCom;
    private javax.swing.JTextField jtPorcHon;
    private javax.swing.JTextField jtPorcInt;
    private javax.swing.JTextField jtValorCuota;
    // End of variables declaration//GEN-END:variables

//    private Ventas obtenerVentasFrame() {
//        JInternalFrame[] frames = getDesktopPane().getAllFrames();
//        for (JInternalFrame frame : frames) {
//            if (frame instanceof Ventas) {
//                return (Ventas) frame;
//            }
//        }
//        return null; // Devuelve null si no se encuentra el frame "AltaClientes"
//    }
    public void agregarElementoAComboBox(Venta dato) {
        jVenta.addItem(dato);
    }

    public void borrar() {
        jForma.removeAllItems();
        jVenta.removeAllItems();
        jcMoneda.removeAllItems();
        jdPago.removeAll();
        jdVto.setDate(null);
        jtCantCuotas.removeAll();
        jtComi.removeAll();
        jtDesc.removeAll();
        jtHono.removeAll();
        jtPorcInt.removeAll();
        jtMonto.removeAll();
        jtPorcCom.removeAll();
        jtPorcHon.removeAll();
        jtValorCuota.removeAll();
        jtInteres.removeAll();
    }

    public void llenarTipoPago() {
        jForma.addItem("");
        jForma.addItem("Efectivo");
        jForma.addItem("Cheque Bancario");
        jForma.addItem("Transferencia Bancaria");
        jForma.addItem("Hipoteca");
        jForma.addItem("Adelanto");
        jForma.addItem("Plan de Pago");

    }

    public void llenarMoneda() {
        jcMoneda.addItem("");
        jcMoneda.addItem("Pesos");
        jcMoneda.addItem("Dolares");
    }

    private void pagoContado() {

        Venta ven = (Venta) jVenta.getSelectedItem();
        String des = jtDesc.getText();
        String fPag = (String) jForma.getSelectedItem();
        LocalDate fechP = jdPago.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        double monto = Double.parseDouble(jtMonto.getText());
        String mon = (String) jcMoneda.getSelectedItem();
        double hon = Double.parseDouble(jtHono.getText());
        double com = Double.parseDouble(jtComi.getText());

        entidades.PagoVenta p = new entidades.PagoVenta(ven, des, fPag, fechP, monto, mon, hon, com);
        PagoVentaData pData = new PagoVentaData();

        pData.agregarPagoVenta(p);
       
        dispose();
    }

    private void pagoCuotas() {

        Venta ven = (Venta) jVenta.getSelectedItem();
        String des = jtDesc.getText();
        String fPag = (String) jForma.getSelectedItem();
        LocalDate fechP = jdPago.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        double monto = Double.parseDouble(jtMonto.getText());
        int cCuota = Integer.parseInt(jtCantCuotas.getText());
        double vCuota = Double.parseDouble(jtValorCuota.getText());
        LocalDate vto = jdVto.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        double intMora = Double.parseDouble(jtInteres.getText());
        String mon = (String) jcMoneda.getSelectedItem();
        double hon = Double.parseDouble(jtHono.getText());
        double com = Double.parseDouble(jtComi.getText());

        entidades.PagoVenta p = new entidades.PagoVenta(ven, des, fPag, fechP, monto, cCuota, vCuota, vto, intMora, mon, hon, com);
        PagoVentaData pData = new PagoVentaData();

        pData.agregarPagoVenta(p);
       
        dispose();
    }

    private void controlDeEntrada() {
        
        if (jForma.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, "Seleccione la Forma de Pago!!.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jVenta.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una Venta!!.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jdPago.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Seleccione la Fecha de Pago!!.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jcMoneda.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, "Seleccione el Tipo de Moneda!!.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jtCantCuotas.isEnabled()&&jtCantCuotas.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Indique la cantidad de Cuotas!!.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jtComi.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falta el monto de comisión!!.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jtPorcCom.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el porcentaje de Comisión!!.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jtPorcHon.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el porcentaje de los Honorarios!!.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jtHono.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falta el monto de los honorarios!!.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jtDesc.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falta completar el campo Descripción!!.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jdVto.isEnabled()&&jdVto.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Indique la fecha del 1er. Vencimiento!!.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jtPorcInt.isEnabled()&& jtPorcInt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el porcentaje de Interés!!.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jtMonto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el monto pagado!!.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jtValorCuota.isEnabled() && jtValorCuota.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese el valor de las cuotas!!.", "Error!", JOptionPane.ERROR_MESSAGE);
        }

        if (!jtMonto.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "Ingrese un Importe válido! (solo números).",
                    "Error en el Monto Ingresado", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(jtCantCuotas.isEnabled()){
             if (!jtCantCuotas.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "Ingrese una cantidad válida! (solo números).",
                    "Error en Cantidad de Cuotas", JOptionPane.ERROR_MESSAGE);
            return;
        }
        }
        if(jtValorCuota.isEnabled()){
             if (!jtValorCuota.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "Ingrese un Importe válido! (solo números).",
                    "Error en el Valor de la Cuota", JOptionPane.ERROR_MESSAGE);
            return;
        }
        }
        if(jtPorcInt.isEnabled()){
            if (!jtPorcInt.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "Ingrese un porcentaje de Interés válido! (solo números).",
                    "Error en el porcentaje de Interés", JOptionPane.ERROR_MESSAGE);
            return;
        }
        }
        
        if (!jtPorcHon.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "Ingrese un porcentaje de Honorarios válido! (solo números).",
                    "Error en el porcentaje de Honorarios", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!jtPorcCom.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "Ingrese un porcentaje de Comisión válido! (solo números).",
                    "Error en el porcentaje de Comisión", JOptionPane.ERROR_MESSAGE);
            return;
        }

    }
}
