/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Enums.TipoCliente;
import static Vistas.Menu.Escritorio;
import accesoDatos.ClienteData;
import accesoDatos.EscribanoData;
import accesoDatos.InmuebleData;
import accesoDatos.VentaData;
import entidades.Cliente;
import entidades.Conyugue;
import entidades.Escribano;
import entidades.Inmueble;
import entidades.Propietario;
import entidades.Venta;
import java.awt.Graphics;
import java.awt.Image;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Compaq
 */
public class Ventas extends javax.swing.JInternalFrame {

    InmuebleData iData = new InmuebleData();
    Inmueble prop = new Inmueble();
// Declarar una variable de instancia para el JInternalFrame
//    private ListaInmuebleVenta listaInmuebleVentaFrame;
    private PagoVenta pagoVentaFrame;

    public Ventas() {
        initComponents();
        llenarCombo();
        llenarInmueble();
        llenarCliente();
        llenarEscribano();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon(getClass().getResource("/Iconos/61911070.jpg"));
            Image image = icon.getImage();
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jdFecha = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlinmueble = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDetalles = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTVenta = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jrPes = new javax.swing.JRadioButton();
        jrDol = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jcescritura = new javax.swing.JComboBox<>();
        jConyugue = new javax.swing.JComboBox<>();
        jEscribano = new javax.swing.JComboBox<>();
        jCliente = new javax.swing.JComboBox<>();
        jpropietario = new javax.swing.JComboBox<>();
        jInmueble = new javax.swing.JComboBox<>();

        setClosable(true);
        setFrameIcon(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(653, 451));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nueva Venta");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jdFecha.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Inmueble:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cliente: ");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Conyugue: ");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Escribano: ");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Propietario: ");

        jTDetalles.setBorder(new javax.swing.border.MatteBorder(null));
        jTDetalles.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTDetalles);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Detalles de venta.");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precio: ");

        jTVenta.setMinimumSize(new java.awt.Dimension(149, 24));

        jBGuardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBGuardar.setText("Guardar Venta");
        jBGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Moneda: ");

        jrPes.setText("ARS");
        jrPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrPesActionPerformed(evt);
            }
        });

        jrDol.setText("US$");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Escriturizacion: ");

        jConyugue.setMinimumSize(new java.awt.Dimension(160, 26));
        jConyugue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConyugueActionPerformed(evt);
            }
        });

        jEscribano.setMinimumSize(new java.awt.Dimension(160, 26));

        jCliente.setMinimumSize(new java.awt.Dimension(160, 26));
        jCliente.setName(""); // NOI18N
        jCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jClienteItemStateChanged(evt);
            }
        });
        jCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClienteActionPerformed(evt);
            }
        });

        jpropietario.setMinimumSize(new java.awt.Dimension(149, 26));
        jpropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpropietarioActionPerformed(evt);
            }
        });

        jInmueble.setMinimumSize(new java.awt.Dimension(160, 26));
        jInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInmuebleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcescritura, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jrPes, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jrDol, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jpropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jlinmueble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jEscribano, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jConyugue, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(45, 45, 45))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jdFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlinmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jpropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jrPes)
                            .addComponent(jrDol))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jcescritura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jConyugue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jEscribano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrPesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrPesActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // TODO add your handling code here:
        if (jdFecha.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Debe ingresar la Fecha de Venta!!.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (jInmueble.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar la propiedad en Venta!!.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (jCliente.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar el Cliente!!.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (jEscribano.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar el nombre del Escribano!!.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (jTVenta.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falta ingresar el precio de venta!!.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }  else if (jcescritura.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar el estado de la Escriturización!!.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (jTDetalles.equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar los detalles de la venta!!.", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!jTVenta.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "Ingrese un importe válido! (solo números).",
                    "Error en el DNI", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Venta ven = null;
        VentaData vData = new VentaData();
        Conyugue con;
        Escribano esc;
        Cliente cli;
        Inmueble inm;
        Propietario prop;
        String mon = null;

        LocalDate fecha = jdFecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        inm = (Inmueble) jInmueble.getSelectedItem();
        prop = inm.getProp();
        cli = (Cliente) jCliente.getSelectedItem();
        con = (Conyugue) jConyugue.getSelectedItem();
        esc = (Escribano) jEscribano.getSelectedItem();
        double pVenta = Double.parseDouble(jTVenta.getText());
        if (jrPes.isSelected()) {
            mon = "Pesos";
        } else if (jrDol.isSelected()) {
            mon = "Dolares";
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar el tipo de moneda.");
        }
        String escritura = (String) jcescritura.getSelectedItem();
        String det = jTDetalles.getText();
        int resp = JOptionPane.showConfirmDialog(null, "¿Desea guardar los datos ingresados?", "Atención!",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (resp == 0) {
            ven = new Venta(fecha, inm, prop, cli, con, esc, pVenta, mon, det, escritura);

            vData.agregarVenta(ven);

            pagoVentaFrame = new PagoVenta();
            Menu.Escritorio.add(pagoVentaFrame);
            
             int x = (getWidth() - pagoVentaFrame.getWidth()) / 3;
        int y = (getHeight() - pagoVentaFrame.getHeight()) / 3;
        pagoVentaFrame.setLocation(x, y);
        pagoVentaFrame.toFront();
            pagoVentaFrame.setVisible(true);
            agregarDatoAComboBoxPago(ven);
            dispose();
        }

    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jConyugueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConyugueActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jConyugueActionPerformed

    private void jClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClienteActionPerformed
        // TODO add your handling code here:

        if (jCliente.getSelectedItem()!= null) {
            Cliente c = (Cliente) jCliente.getSelectedItem();

            if (c.getTipo() == TipoCliente.PERSONA_FISICA) {
                jConyugue.setEnabled(true);
                jConyugue.addItem(c.getConyugue());
            } else if (c.getTipo() == TipoCliente.PERSONA_JURIDICA) {
                jConyugue.setSelectedItem(null);
                jConyugue.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jClienteActionPerformed

    private void jClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jClienteItemStateChanged
        // TODO add your handling code here:
        jConyugue.removeAllItems();

    }//GEN-LAST:event_jClienteItemStateChanged

    private void jpropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpropietarioActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jpropietarioActionPerformed

    private void jInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInmuebleActionPerformed
        // TODO add your handling code here:
        if(jInmueble.getSelectedItem()!= null){
             Inmueble in = (Inmueble) jInmueble.getSelectedItem();
//             System.out.println(in.getProp());
        jpropietario.addItem(in.getProp());
        jlinmueble.setText(in.getTipo() + " - " + in.getDireccion() + " - " + in.getSuperficie());
        }
       
    }//GEN-LAST:event_jInmuebleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGuardar;
    private javax.swing.JComboBox<Cliente> jCliente;
    private javax.swing.JComboBox<Conyugue> jConyugue;
    private javax.swing.JComboBox<Escribano> jEscribano;
    private javax.swing.JComboBox<Inmueble> jInmueble;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTDetalles;
    private javax.swing.JTextField jTVenta;
    private javax.swing.JComboBox<String> jcescritura;
    private com.toedter.calendar.JDateChooser jdFecha;
    private javax.swing.JLabel jlinmueble;
    private javax.swing.JComboBox<Propietario> jpropietario;
    private javax.swing.JRadioButton jrDol;
    private javax.swing.JRadioButton jrPes;
    // End of variables declaration//GEN-END:variables

    public void llenarCombo() {
        jcescritura.addItem("");
        jcescritura.addItem("Pendiente");
        jcescritura.addItem("En revisión");
        jcescritura.addItem("Aprobada por las partes");
        jcescritura.addItem("Firmada");
        jcescritura.addItem("En proceso de inscripcion");
        jcescritura.addItem("Completada");
    }

    private PagoVenta obtenerVentasFrame() {
        JInternalFrame[] frames = getDesktopPane().getAllFrames();
        for (JInternalFrame frame : frames) {
            if (frame instanceof PagoVenta) {
                return (PagoVenta) frame;
            }
        }
        return null; // Devuelve null si no se encuentra el frame "AltaClientes"
    }

    public void agregarDatoAComboBoxPago(Venta dato) {
        PagoVenta pago = obtenerVentasFrame(); // Obtén la referencia al JInternalFrame "AltaClientes"
        if (pago != null) {
            pago.agregarElementoAComboBox(dato); // Agrega el dato al JComboBox "jcombo2" en "AltaClientes"
        }
    }

    public void llenarInmueble() {
        jInmueble.addItem(null);
        InmuebleData inData = new InmuebleData();
        for (Inmueble i : inData.buscarPropiedadesAlqVta("venta", true)) {
            jInmueble.addItem(i);
            System.out.println(i.getDireccion()+" - "+i.getProp());
        }
    }

    private void llenarCliente() {
        jCliente.addItem(null);
        ClienteData cData = new ClienteData();
        for (Cliente c : cData.listarTodosClientesActivos()) {
            jCliente.addItem(c);
        }

    }

    private void llenarEscribano() {
        jEscribano.addItem(null);
        EscribanoData eData = new EscribanoData();
        for (Escribano e : eData.listarEscribanos()) {
            jEscribano.addItem(e);
        }
    }

}
